config/routes.rb
Rails.application.routes.draw do
  root "chapters#index"
  resources :chapters, except: [:index]
  resources :blocks, only: [:create, :edit, :destroy, :update]
  # маршруты для переключения принадлежности блока
  get "/blocks/:id/switch", to: "blocks#switch", as: "switch_block"
  patch "/blocks/:id/switch", to: "blocks#switch_update", as: "switch_update"

  resources :errors
  resources :subsections, except: [:index, :new]

  resources :tasks

  get 'ajax/show'
  get 'ajax/customers_show'
  get 'ajax/carriers_show'
  get 'ajax/cars'
  get 'ajax/drivers'
  get 'ajax/towns_from'
  get 'ajax/towns_in'

  namespace :cargo do
    resources :carriers
    resources :customers
    resources :cars, except: [:new, :index]
    get "/carrier/:id/cars/new", to: "cars#new", as: "new_car"
    resources :drivers, except: [:new, :index]
    get "/carrier/:id/drivers/new", to: "drivers#new", as: "new_driver"
    resources :contacts, only: [:destroy, :edit, :update]
    get "/orders/:id/file_exist", to: "orders#file_exist", as: "file_exist"
    get "/orders/:id/file_exist_i", to: "orders#file_exist_i", as: "file_exist_i"
    get "/orders/arhive", to: "orders#arhive", as: "arhive"
    post "/orders/exits_folder", to: "orders#folder", as: "exist_folder"
    post "/orders/exits_doc", to: "orders#doc", as: "exist_doc"
    resources :orders
    get "/towns/parsing", to: "towns#parsing", as: "parsing_towns"
    resources :towns
  end
end

app/models/cargo.rb
module Cargo
  def self.table_name_prefix
    "cargo_"
  end
end

app/models/cargo/adress_load.rb
class Cargo::AdressLoad < ApplicationRecord
  has_many :orders
  belongs_to :customer
end

app/models/cargo/adress_reload.rb
class Cargo::AdressReload < ApplicationRecord
  has_many :orders
  belongs_to :customer
end

app/models/cargo/car.rb
class Cargo::Car < ApplicationRecord
  validates :reg_mark, presence: true, uniqueness: true

  belongs_to :carrier, optional: true
  has_many :orders
end

app/models/cargo/carrier.rb
class Cargo::Carrier < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :cars, dependent: :destroy
  has_many :drivers, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :orders
end

app/models/cargo/contact.rb
class Cargo::Contact < ApplicationRecord
  belongs_to :carrier, optional: true
  belongs_to :customer, optional: true
  belongs_to :driver, optional: true
end

app/models/cargo/customer.rb
class Cargo::Customer < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :contacts, dependent: :destroy
  has_many :orders
  has_many :adress_loads
  has_many :adress_reloads

  has_many :customer_gruzs, dependent: :destroy
  has_many :gruzs, through: :customer_gruzs
end

app/models/cargo/customer_gruz.rb
class Cargo::CustomerGruz < ApplicationRecord
  belongs_to :customer
  belongs_to :gruz
end

app/models/cargo/driver.rb
class Cargo::Driver < ApplicationRecord
  validates :name, presence: true

  belongs_to :carrier, optional: true
  has_many :contacts, dependent: :destroy
  has_many :orders
end

app/models/cargo/gruz.rb
class Cargo::Gruz < ApplicationRecord
  has_many :orders

  has_many :customer_gruzs, dependent: :destroy
  has_many :customer, through: :customer_gruzs
end

app/models/cargo/order.rb
class Cargo::Order < ApplicationRecord
  COLOR = ['', 'primary', 'success', 'dark', 'secondary', 'danger']

  belongs_to :customer, optional: true
  belongs_to :carrier, optional: true
  belongs_to :car, optional: true
  belongs_to :driver, optional: true
  has_one :payment
  has_one :adress_load
  has_one :adress_reload
  has_one :gruz

  belongs_to :town_from, class_name: "Town", foreign_key: "town_from_id", optional: true
  belongs_to :town_in, class_name: "Town", foreign_key: "town_in_id", optional: true
end

app/models/cargo/payment.rb
class Cargo::Payment < ApplicationRecord
  belongs_to :order
end

app/models/cargo/town.rb
class Cargo::Town < ApplicationRecord
end

app/controllers/cargo/carriers_controller.rb
class Cargo::CarriersController < ApplicationController
  layout "cargo"

  before_action :set_cargo_carrier, only: %i[ show edit update destroy ]

  # GET /cargo/carriers
  def index
    @cargo_carriers = Cargo::Carrier.all
  end

  # GET /cargo/carriers/1
  def show
  end

  # GET /cargo/carriers/new
  def new
    @cargo_carrier = Cargo::Carrier.new
  end

  # GET /cargo/carriers/1/edit
  def edit
  end

  # POST /cargo/carriers
  def create
    @cargo_carrier = Cargo::Carrier.new(cargo_carrier_params)

    if @cargo_carrier.save
      AddContact.(@cargo_carrier, params)
      flash[:success] = "Carrier was successfully created."
      redirect_to @cargo_carrier
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @cargo_carrier.update(cargo_carrier_params)
      AddContact.(@cargo_carrier, params)
      flash[:success] = "Carrier was successfully updated."
      redirect_to @cargo_carrier
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cargo/carriers/1
  def destroy
    @cargo_carrier.destroy
    flash[:success] = "Carrier was successfully destroyed."
    redirect_to cargo_carriers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo_carrier
      @cargo_carrier = Cargo::Carrier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_carrier_params
      params.require(:cargo_carrier).permit(:name, :inn, :ogrn, :passport, :adress)
    end
end

app/controllers/cargo/cars_controller.rb
class Cargo::CarsController < ApplicationController
  layout "cargo"

  before_action :set_cargo_car, only: %i[ show edit update destroy ]
  before_action :set_cargo_carrier, only: %i[ new create ]

  # GET /cargo/cars/1
  def show
  end

  # GET /cargo/cars/new
  def new
    @cargo_car = Cargo::Car.new
  end

  # GET /cargo/cars/1/edit
  def edit
  end

  # POST /cargo/cars
  def create
    @cargo_car = Cargo::Car.new(cargo_car_params)
    @cargo_car.carrier = @carrier

    if @cargo_car.save
      @carrier.cars.push(@cargo_car)
      flash[:success] = "Car was successfully created."
      redirect_to @cargo_car
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cargo/cars/1
  def update
    if @cargo_car.update(cargo_car_params)
      flash[:success] = "Car was successfully updated."
      redirect_to @cargo_car
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cargo/cars/1
  def destroy
    @cargo_car.destroy
    flash[:success] = "Car was successfully destroyed."
    redirect_to cargo_carrier_path(@cargo_car.carrier)
  end

  private

  def set_cargo_carrier
    @carrier = Cargo::Carrier.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_cargo_car
    @cargo_car = Cargo::Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cargo_car_params
    params.require(:cargo_car).permit(:brand, :reg_mark, :p_mark)
  end
end

app/controllers/cargo/contacts_controller.rb
class Cargo::ContactsController < ApplicationController
  layout "cargo"

  before_action :set_cargo_contact

  def edit
  end

  def update
    if @cargo_contact.update(cargo_contact_params)
      flash[:success] = "Contact was successfully updated."
      redirect_to cargo_customers_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cargo_contact.destroy
    flash[:success] = "Contact was successfully destroyed."
    redirect_to cargo_customers_path
  end

  private

  def set_cargo_contact
    @cargo_contact = Cargo::Contact.find(params[:id])
  end

  def cargo_contact_params
    params.require(:cargo_contact).permit(:name_contact, :tel, :email)
  end
end

app/controllers/cargo/customers_controller.rb
class Cargo::CustomersController < ApplicationController
  layout "cargo"

  before_action :set_cargo_customer, only: %i[ show edit update destroy ]

  def index
    @cargo_customers = Cargo::Customer.all
  end

  def show
  end

  def new
    @cargo_customer = Cargo::Customer.new
  end

  def edit
  end

  def create
    @cargo_customer = Cargo::Customer.new(cargo_customer_params)

    if @cargo_customer.save
      AddContact.(@cargo_customer, params)
      flash[:success] = "Customer was successfully created."
      redirect_to @cargo_customer
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @cargo_customer.update(cargo_customer_params)
      AddContact.(@cargo_customer, params)
      flash[:success] = "Customer was successfully updated."
      redirect_to @cargo_customer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cargo_customer.destroy
    flash[:success] = "Customer was successfully destroyed."
    redirect_to cargo_customers_url
  end

  private

  def set_cargo_customer
    @cargo_customer = Cargo::Customer.find(params[:id])
  end

  def cargo_customer_params
    params.require(:cargo_customer).permit(:name, :inn, :ogrn, :passport, :adress)
  end
end

app/controllers/cargo/drivers_controller.rb
class Cargo::DriversController < ApplicationController
  layout "cargo"

  before_action :set_cargo_driver, only: %i[ show edit update destroy ]
  before_action :set_cargo_carrier, only: %i[ new create ]

  def show
  end

  def new
    @cargo_driver = Cargo::Driver.new
  end

  def edit
  end

  def create
    @cargo_driver = Cargo::Driver.new(cargo_driver_params)
    @cargo_driver.carrier = @carrier

    if @cargo_driver.save
      AddContact.(@cargo_driver, params)
      @carrier.drivers.push(@cargo_driver)
      flash[:success] = "Driver was successfully created."
      redirect_to @cargo_driver
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @cargo_driver.update(cargo_driver_params)
      AddContact.(@cargo_driver, params)
      flash[:success] = "Driver was successfully updated."
      redirect_to @cargo_driver
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cargo_driver.destroy
    flash[:success] = "Driver was successfully destroyed."
    redirect_to cargo_carrier_path(@cargo_driver.carrier)
  end

  private

  def set_cargo_carrier
    @carrier = Cargo::Carrier.find(params[:id])
  end

  def set_cargo_driver
    @cargo_driver = Cargo::Driver.find(params[:id])
  end

  def cargo_driver_params
    params.require(:cargo_driver).permit(:name, :passport, :vy)
  end
end

app/controllers/cargo/orders_controller.rb
require 'iconv'
require 'htmltoword'

class Cargo::OrdersController < ApplicationController
  layout "cargo"

  before_action :set_cargo_order, except: [:index, :arhive, :new, :create]

  def index
    @cargo_orders = Cargo::Order.where('status < 3').order(id: :desc)
  end

  def arhive
    @cargo_orders = Cargo::Order.where('status > 2').order(id: :desc)
    render "index"
  end

  # GET /cargo/orders/1
  def show
  end

  # GET /cargo/orders/new
  def new
    @cargo_order = Cargo::Order.new
  end

  # GET /cargo/orders/1/edit
  def edit
  end

  # POST /cargo/orders
  def create
    @cargo_order = Cargo::Order.new(cargo_order_params)
    AddReference.(@cargo_order, params)

    if @cargo_order.save
      flash[:success] = "Order was successfully created."
      redirect_to cargo_orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    AddReference.(@cargo_order, params)

    if @cargo_order.update(cargo_order_params)
      redirect_to cargo_orders_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cargo_order.destroy
    flash[:success] = "Order was successfully destroyed."
    redirect_to cargo_orders_url
  end

  def exist
  end

  def folder
    path = "../../requests/requests/#{params[:name_folder]}"
    Dir.mkdir("#{path}") unless File.directory?("#{path}")
  end

  def doc
    if params['order_adress_load'].present?
      if Cargo::AdressLoad.find_by(adress: params['order_adress_load']).present?
        adress_load = Cargo::AdressLoad.find_by(adress: params['order_adress_load'])
      else
        adress_load = Cargo::AdressLoad.new(adress: params['order_adress_load'])
      end

      adress_load.customer = @cargo_order.customer
      @cargo_order.adress_load = adress_load
      adress_load.save
    end

    if params['order_adress_reload'].present?
      if Cargo::AdressReload.find_by(adress: params['order_adress_reload']).present?
        adress_reload = Cargo::AdressReload.find_by(adress: params['order_adress_reload'])
      else
        adress_reload = Cargo::AdressReload.new(adress: params['order_adress_reload'])
      end

      adress_reload.customer = @cargo_order.customer
      @cargo_order.adress_reload = adress_reload
      adress_reload.save
    end

    @cargo_order.date_load = params['order_date_load'] if params['order_date_load'].present?
    @cargo_order.date_reload = params['order_date_reload'] if params['order_date_reload'].present?

    if params['gruz_weight'].present? || params['gruz_what_is'].present? || params['gruz_volume'].present?
      if  Cargo::Gruz.find_by(weight: params['gruz_weight'], volume: params['gruz_volume'], what_is: params['gruz_what_is']).present?
        gruz = Cargo::Gruz.find_by(weight: params['gruz_weight'], volume: params['gruz_volume'], what_is: params['gruz_what_is'])
      else
        gruz = Cargo::Gruz.new(weight: params['gruz_weight'], volume: params['gruz_volume'], what_is: params['gruz_what_is'])
        gruz.save
      end
    end

    @cargo_order.gruz = gruz
    @cargo_order.save
    unless @cargo_order.customer.gruzs.include?(gruz)
      @cargo_order.customer.gruzs.push(gruz)
    end

    text = params['text_order']
    name_folder = params['name_folder']
    path = "../../requests/requests/#{name_folder}"
    Dir.mkdir("#{path}") unless File.directory?("#{path}")

    path_file = "../../requests/requests/#{name_folder}/my_order.html"
    path_img = "../../requests/requests/#{name_folder}/signature.png"
    path_docx = "../../requests/requests/#{name_folder}/my_order.docx"
  end

  def file_exist
    @customer = @cargo_order.customer
  end

  def file_exist_i
    @customer = Cargo::Customer.find 1
    render "file_exist"
  end

  private

  def set_cargo_order
    @cargo_order = Cargo::Order.find(params[:id])
  end

  def cargo_order_params
    params.require(:cargo_order).permit(:status, :folder)
  end
end

app/controllers/cargo/towns_controller.rb
class Cargo::TownsController < ApplicationController
  require 'open-uri'
  require 'nokogiri'

  layout "cargo"

  before_action :set_cargo_town, only: %i[ show edit update destroy ]

  def parsing
    @uri = "https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8"

    File.delete('./log/dev/logfile.log')
    logger = Logger.new('./log/dev/logfile.log')

    doc = Nokogiri::HTML(URI.open(@uri))
    tbody = doc.css('tbody')

    tbody.css('tr').each.with_index do |tr, ind|
      if tr.css('td').size > 3
        name = tr.css('td')[2].css('a').text
        name = name.gsub(/(призн.)/, '') if name.match('призн.')
        region = tr.css('td')[3].css('a').text
        logger.debug "#{name.strip} - #{region}"
        Cargo::Town.create(title: name, region: region)
      end
    end

    redirect_to cargo_towns_path
  end

  # GET /cargo/towns
  def index
    @cargo_towns = Cargo::Town.all
  end

  # GET /cargo/towns/1
  def show
  end

  # GET /cargo/towns/new
  def new
    @cargo_town = Cargo::Town.new
  end

  # GET /cargo/towns/1/edit
  def edit
  end

  # POST /cargo/towns
  def create
    @cargo_town = Cargo::Town.new(cargo_town_params)

    if @cargo_town.save
      redirect_to @cargo_town, notice: "Town was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cargo/towns/1
  def update
    if @cargo_town.update(cargo_town_params)
      redirect_to @cargo_town, notice: "Town was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cargo/towns/1
  def destroy
    @cargo_town.destroy
    redirect_to cargo_towns_url, notice: "Town was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cargo_town
    @cargo_town = Cargo::Town.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cargo_town_params
    params.require(:cargo_town).permit(:title, :region)
  end
end

app/views/cargo/orders/_form.html.erb
<%= form_with(model: cargo_order) do |form| %>
  <% if cargo_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cargo_order.errors.count, "error") %> prohibited this cargo_order from being saved:</h2>

      <ul>
        <% cargo_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :status %>
  <div class="row border-bottom pb-2">
    <div class="position-relative col-2 p-0">
      <%= cargo_order_customer_exist(cargo_order) %>
      <div class="position-absolute bg-light p-1" id="customers_show" style="display: none;"></div>
    </div>

    <div class="position-relative col-2 p-0">
      <%= cargo_order_town_from_exist(cargo_order) %>
      <div class="position-absolute border border-dark bg-light p-1 w-100" id="town_from_show" style="display: none;"></div>
    </div>

    <div class="position-relative col-2 p-0">
      <%= cargo_order_town_in_exist(cargo_order) %>
      <div class="position-absolute border border-dark bg-light p-1 w-100" id="town_in_show" style="display: none;"></div>
    </div>

    <div class="position-relative col-2 p-0">
      <%= cargo_order_carrier_exist(cargo_order) %>
      <div class="position-absolute border border-dark bg-light p-1 w-100" id="carriers_show"
        style="display: none; z-index: 1;">
      </div>

      <div class="position-absolute" id="cars_drivers"
        style="display: <%= cargo_order.car.present? ? "block" : "none" %>;">
        <%= cargo_order_car_exist(cargo_order) %>
        <%= cargo_order_driver_exist(cargo_order) %>
      </div>
    </div>

    <div class="position-relative col-2 p-0">
      <%= cargo_order_payment_exist(cargo_order) %>
    </div>

    <%= form.hidden_field :folder, id: "folder-hidden"%>

    <div class="position-relative col-2 p-0">
      <%= form.submit "Exist order", class: "btn btn-success m-2" %>
    </div>
  </div>
<% end %>

app/views/cargo/orders/_form_doc.html.erb
<%= form_with url: cargo_exist_doc_path do |form| %>
  <%= form.hidden_field :name_folder, value: "#{@cargo_order.folder}", id: "name-folder-hidden-to-file"%>

  <br />
    <br />
      <br />
  <div>
    <%= form.hidden_field :id, value: @cargo_order.id %>
    Заявка-договор №<%= form.text_field :order_number, value: "#{name_order_to_doc}", style: "width: 80px;" %>
    от <%= form.text_field :order_date, value: "#{date_order}" %>
  </div>
  <div>
    ЗАКАЗЧИК: <%= form.text_field :cus_name, value: "#{@cargo_order.customer.name}" %>
    ИНН: <%= form.text_field :cus_inn, value: "#{@cargo_order.customer.inn}" %>
    ОГРН: <%= form.text_field :cus_ogrn, value: "#{@cargo_order.customer.ogrn}" %>
  </div>

  <div>
    ПЕРЕВОЗЧИК: <%= form.text_field :car_name, value: "#{@cargo_order.carrier.name if @cargo_order.carrier.present? }" %>
    ИНН: <%= form.text_field :car_inn, value: "#{@cargo_order.carrier.inn if @cargo_order.carrier.present? }" %>
    ОГРН: <%= form.text_field :car_ogrn, value: "#{@cargo_order.carrier.ogrn if @cargo_order.carrier.present? }" %>
  </div>
  <div>
    Маршрут: <%= form.text_field :order_route, style: "width: 600px;", value: "#{@cargo_order.town_from.title}(#{@cargo_order.town_from.region}) - #{@cargo_order.town_in.title}(#{@cargo_order.town_in.region})" %>
  </div>
  <div>
     Дата загрузки: <%= form.text_field :order_date_load, style: "width: 900px;", value: "#{
        if @cargo_order.date_load.present?
          @cargo_order.date_load
        else
          "#{Time.now.strftime("%d.%m.%Y")} по согласованию."
        end
        }" %>
  </div>
  <div>
    Адрес загрузки: <%= form.text_field :order_adress_load, style: "width: 900px;", value: "#{@cargo_order.adress_load.adress if @cargo_order.adress_load.present? }" %>
  </div>
  <div>
     Дата выгрузки: <%= form.text_field :order_date_reload, style: "width: 900px;", value: "#{
        if @cargo_order.date_reload.present?
          @cargo_order.date_reload
        else
          "#{Time.now.strftime("%d.%m.%Y")} по согласованию."
        end
        }" %>
  </div>
  <div>
    Адрес выгрузки: <%= form.text_field :order_adress_reload, style: "width: 900px;", value: "#{@cargo_order.adress_reload.adress if @cargo_order.adress_reload.present? }" %>
  </div>
  <div>
    Характеристики груза:<br/>
    Чот везем: <%= form.text_field :gruz_what_is, style: "width: 500px;", value: "#{ @cargo_order.gruz.what_is if @cargo_order.gruz.present? && @cargo_order.gruz.what_is.present? }" %>
  </div>
  <div>
    Вес: <%= form.text_field :gruz_weight, style: "width: 100px;", value: "#{ @cargo_order.gruz.weight if @cargo_order.gruz.present? && @cargo_order.gruz.weight.present? }" %>
  </div>
  <div>
    Объем: <%= form.text_field :gruz_volume, style: "width: 100px;", value: "#{ @cargo_order.gruz.volume if @cargo_order.gruz.present? && @cargo_order.gruz.volume.present? }"  %>
  </div>

  <!--%= image_tag("signature")%-->
  <div class="position-relative col-2 p-0">
    <%= form.submit "Exits file", class: "btn btn-success m-2 d-inline-block" %>
    <%= link_to "Перейти к ИП", cargo_file_exist_path(@cargo_order), class: 'btn btn-success m-2 d-inline-block' %>
    <%= link_to "Перейти к Я", cargo_file_exist_i_path(@cargo_order), class: 'btn btn-success m-2 d-inline-block' %>
  </div>
<% end %>

app/views/cargo/orders/_form_folder.html.erb
<div class="border col-6">
  <%= form_with url: cargo_exist_folder_path do |form| %>
    <%= form.label :query, "Name folder:" %>
    <div id="name-folder" class="border d-inline-block" style="min-width: 60%;">
      <%= @cargo_order.folder.present? ? @cargo_order.folder : date_name_folder %>
    </div>
    <%= form.hidden_field :name_folder, value: "#{@cargo_order.folder}", id: "name-folder-hidden"%>
    <%= form.submit "Exist folder", class: "btn btn-success d-inline-block"  %>
  <% end %>
</div>

app/views/cargo/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <div class="row border-bottom border-dark text-<%= Cargo::Order::COLOR[order.status] %>"
    style="height: 30px;">

    <% if order.customer.present? %>
      <div class="col-3">
        <div class="d-inline-block m-0" style="vertical-align: top;"><%=order.id%>|</div>
        <div class="d-inline-block m-0" style="overflow: hidden; white-space: nowrap; width: 90%;">
          <% unless order.customer.contacts.first.nil? %>
            <%= order.customer.contacts.first.tel %>:
          <% end %>
          <div class="d-inline-block m-0">
            <%= link_to order.customer.name,
              cargo_customer_path(order.customer),
              class: "text-#{Cargo::Order::COLOR[order.status]}",
              style: "text-decoration: none;" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col-2" style="overflow: hidden; white-space: nowrap;">
      <% if order.town_from.present? %>
        <%= order.town_from.title %>
      <% end %>
      -
      <% if order.town_in.present? %>
        <%= order.town_in.title %>
      <% end %>
    </div>

    <% if order.carrier.present? %>
      <div class="col-3">
        <div class=" d-inline-block m-0 p-0" style="width: 100%; overflow: hidden; white-space: nowrap; height: 25px;">
          <div class=" d-inline-block ml-1" style="vertical-align: top;">
            <% unless order.carrier.contacts.first.nil? %>
              <%= order.carrier.contacts.first.tel %>:
            <% end %>
          </div>
          <div class=" d-inline-block m-0"
            style="max-width: 250px; overflow: hidden; m-0">
            <%= link_to order.carrier.name,
              cargo_carrier_path(order.carrier),
              class: "text-#{Cargo::Order::COLOR[order.status]}",
              style: "text-decoration: none;" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col-1">
      <%= order.payment.present? ? order.payment.sum : "sum" %>
    </div>

    <div class="col-1">
      <%= order.payment.present? ? order.payment.sin : "sin" %>
    </div>

    <div class="col-1">
      <div class="d-inline-block">
        <%= link_to "S", cargo_order_path(order.id),
          class: "text-#{Cargo::Order::COLOR[order.status]}",
          style: "text-decoration: none;" %>
      </div>
      <div class="d-inline-block">
        <%= form_with(model: order) do |form| %>
          <%= form.select(:status, options_for_select([1,2,3,4,5],order.status)) %>
          <%= form.submit "e", class: "btn btn-#{Cargo::Order::COLOR[order.status]} px-2 py-0 m-0",
            style: "height: 24px; vertical-align: top;" %>
        <% end %>
      </div>
    </div>
    <div class="col-1">
      <%= order.created_at.strftime("%d-%m-%y")  %>
    </div>
  </div>
</div>

app/views/cargo/orders/edit.html.erb
<div class="row my-2" style="position: relative;">
  <div class="border col-2" id="new-folder">
    <h2>Edit order</h2>
  </div>

  <%= render "form_folder", cargo_order: @cargo_order %>
</div>

<%= render "form", cargo_order: @cargo_order %>
<%= render "form_doc", cargo_order: @cargo_order %>
<div>
  <%= link_to "Show this order", @cargo_order %> |
  <%= link_to "Back to orders", cargo_orders_path %>
</div>

app/views/cargo/orders/index.html.erb
<div class="row border-bottom pb-2">
  <div class="col-2"><h4>Orders</h4></div>

  <%= link_to "Arhive", cargo_arhive_path, class: "btn btn-success w-auto mx-2" %>
  <%= link_to "New order", new_cargo_order_path, class: "btn btn-success w-auto" %>
</div>

<div id="cargo_orders">
  <% @cargo_orders.each do |cargo_order| %>
    <%= render cargo_order %>
  <% end %>
</div>

app/views/cargo/orders/new.html.erb
<div class="row my-2">
  <div class="border col-2"  id="new-folder">
    <h2>New order</h2>
  </div>

  <%= render "form_folder", cargo_order: @cargo_order %>
</div>

<%= render "form", cargo_order: @cargo_order %>
<!--%= render "form_doc", cargo_order: @cargo_order %-->

app/views/cargo/orders/show.html.erb
<%= render @cargo_order %>

<div>
  <%= link_to "Edit this order", edit_cargo_order_path(@cargo_order), class: "btn btn-success my-2" %>
  <%= link_to "Back to orders", cargo_orders_path, class: "btn btn-success my-2" %>

  <%= button_to "Destroy this order", @cargo_order, method: :delete,
    onclick: "return confirm('Are you sure?')",
    class: "btn btn-danger" %>
</div>