config/routes.rb
Rails.application.routes.draw do
  root "chapters#index"
  resources :chapters, except: [:index]
  resources :blocks, only: [:create, :edit, :destroy, :update]
  # маршруты для переключения принадлежности блока
  get "/blocks/:id/switch", to: "blocks#switch", as: "switch_block"
  patch "/blocks/:id/switch", to: "blocks#switch_update", as: "switch_update"

  resources :errors
  resources :subsections, except: [:index, :new]

  resources :tasks

  get 'ajax/show'
  get 'ajax/customers_show'
  get 'ajax/carriers_show'
  get 'ajax/cars'
  get 'ajax/drivers'
  get 'ajax/towns_from'
  get 'ajax/towns_in'

  namespace :cargo do
    resources :carriers
    resources :customers
    resources :cars, except: [:new, :index]
    get "/carrier/:id/cars/new", to: "cars#new", as: "new_car"
    resources :drivers, except: [:new, :index]
    get "/carrier/:id/drivers/new", to: "drivers#new", as: "new_driver"
    resources :contacts, only: [:destroy, :edit, :update]
    get "/orders/:id/file_exist", to: "orders#file_exist", as: "file_exist"
    get "/orders/:id/file_exist_i", to: "orders#file_exist_i", as: "file_exist_i"
    get "/orders/arhive", to: "orders#arhive", as: "arhive"
    post "/orders/exits_folder", to: "orders#folder", as: "exist_folder"
    post "/orders/exits_doc", to: "orders#doc", as: "exist_doc"
    resources :orders
    get "/towns/parsing", to: "towns#parsing", as: "parsing_towns"
    resources :towns
  end
end

app/models/subsection.rb
class Subsection < ApplicationRecord
  belongs_to :chapter, optional: true
  has_many :blocks, dependent: :destroy

  validates :name, presence: true, length: { maximum:255 }
end

app/controllers/subsections_controller.rb
class SubsectionsController < ApplicationController
  before_action :find_subsection, only: [:show, :edit, :update, :destroy]

  def create
    chapter = Chapter.find params[:chapter_id]
    chapter.subsections.create(subsection_params)

    flash[:success] = I18n.t('subsection.comments.create')
    redirect_to chapter_path(chapter)
  end

  def update
    @subsection.update(subsection_params)

    flash[:success] = I18n.t('subsection.comments.edit')
    redirect_to subsection_path(@subsection)
  end

  def show
  end

  def edit
    @block = Block.new
  end

  def destroy
    @subsection.destroy
    flash[:danger] = I18n.t('subsection.destroy')
    redirect_to chapter_path(@subsection.chapter)
  end

  private

  def subsection_params
    params.require(:subsection).permit(:name)
  end

  def find_subsection
    @subsection = Subsection.find params[:id]
  end
end

app/helpers/subsections_helper.rb
module SubsectionsHelper
end

app/views/subsections/_form.html.erb
<div class="row bg-dark rounded py-2 my-1">
  <%= form_for @subsection, html: { class: "row col-10" } do |f| %>
    <div class="col-10 form-group d-inline-block">
      <%= f.text_field :name, placeholder: 'add subsection', class: "mb-2 form-control p-1 pr-2" %>
    </div>
    <div class="col-2 d-inline-block">
      <%= f.submit "save subsection", class: "w-100 btn btn-primary d-inline-block" %>
    </div>

    <% unless @chapter.nil? %>
      <%= hidden_field_tag :chapter_id, @chapter.id %>
    <% end %>
  <% end %>

  <% unless @subsection.id.nil? %>
    <div class="col-2 align-top">
      <%= button_to "destroy", subsection_path(@subsection.id), method: :delete,
        class: "btn btn-danger w-100",
        onclick: "return confirm('#{t("subsection.comments.destroy")}')"
      %>
    </div>
  <% end %>
</div>

app/views/subsections/_subsection.html.erb
<div class="col-4">
  <%= link_to "#{subsection.name}", subsection_path(subsection.id), class: 'w-100 btn btn-info my-1' %>
</div>

app/views/subsections/edit.html.erb
<%= content_tag :div, (content_tag :h1, "Update \"#{@subsection.name}\""), class: 'col-6 text-center d-inline-block' %>

<%= render 'form' %>
<%= render 'blocks/form' %>

<div>
  <%= render partial: 'blocks/block_edit', collection: @subsection.blocks.order(:number_line) %>
</div>

app/views/subsections/show.html.erb
<div class="text-center">
  <%= link_to (content_tag :div, (content_tag :h1, "#{@subsection.chapter.name}/#{@subsection.name}"), class: 'col-6 text-center d-inline-block'),
    chapter_path(@subsection.chapter.id) %>
  <%= link_to t('message.edit'), edit_subsection_path(@subsection.id), class: 'btn btn-dark col-2' %>
</div>
<% unless @subsection.blocks.empty? %>
  <div>
    <%= render partial: 'blocks/block', collection: @subsection.blocks.order(:number_line) %>
  </div>
<% end %>