config/routes.rb
Rails.application.routes.draw do
  root "chapters#index"
  resources :chapters, except: [:index]
  resources :blocks, only: [:create, :edit, :destroy, :update]
  # маршруты для переключения принадлежности блока
  get "/blocks/:id/switch", to: "blocks#switch", as: "switch_block"
  patch "/blocks/:id/switch", to: "blocks#switch_update", as: "switch_update"

  resources :errors
  resources :subsections, except: [:index, :new]

  resources :tasks

  get 'ajax/show'
  get 'ajax/customers_show'
  get 'ajax/carriers_show'
  get 'ajax/cars'
  get 'ajax/drivers'
  get 'ajax/towns_from'
  get 'ajax/towns_in'

  namespace :cargo do
    resources :carriers
    resources :customers
    resources :cars, except: [:new, :index]
    get "/carrier/:id/cars/new", to: "cars#new", as: "new_car"
    resources :drivers, except: [:new, :index]
    get "/carrier/:id/drivers/new", to: "drivers#new", as: "new_driver"
    resources :contacts, only: [:destroy, :edit, :update]
    get "/orders/:id/file_exist", to: "orders#file_exist", as: "file_exist"
    get "/orders/:id/file_exist_i", to: "orders#file_exist_i", as: "file_exist_i"
    get "/orders/arhive", to: "orders#arhive", as: "arhive"
    post "/orders/exits_folder", to: "orders#folder", as: "exist_folder"
    post "/orders/exits_doc", to: "orders#doc", as: "exist_doc"
    resources :orders
    get "/towns/parsing", to: "towns#parsing", as: "parsing_towns"
    resources :towns
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :chapter, optional: true
  belongs_to :subsection, optional: true
end

app/models/cargo.rb
module Cargo
  def self.table_name_prefix
    "cargo_"
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :blocks, dependent: :destroy
  has_many :subsections, dependent: :destroy

  validates :name, presence: true, length: { maximum:255 }
  validates :name, uniqueness: true
end

app/models/error.rb
class Error < ApplicationRecord
  validates :name, presence: true
end

app/models/subsection.rb
class Subsection < ApplicationRecord
  belongs_to :chapter, optional: true
  has_many :blocks, dependent: :destroy

  validates :name, presence: true, length: { maximum:255 }
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum:255 }
  validates :title, uniqueness: true
end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController

  def customers_show
    @search_customers = params[:search_customers]
    @customers = []
    @customers = Cargo::Customer.where("name LIKE '%#{@search_customers}%'") if @search_customers.present?
  end

  def carriers_show
    @search_carriers = params[:search_carriers]
    @customers = []
    @customers = Cargo::Carrier.where("name LIKE '%#{@search_carriers}%'") if @search_carriers.present?
  end

  def cars
    @cars = Cargo::Carrier.find(params[:id_carrier]).cars
  end

  def drivers
    @drivers = Cargo::Carrier.find(params[:id_carrier]).drivers
  end

  def towns_from
    @search_towns = params[:search_towns]
    @towns = []
    @towns = Cargo::Town.where("title LIKE '%#{@search_towns}%'") if @search_towns.present?
  end

  def towns_in
    @search_towns = params[:search_towns]
    @towns = []
    @towns = Cargo::Town.where("title LIKE '%#{@search_towns}%'") if @search_towns.present?
  end

  # общий поиск по сайту (не гурзоперевозки)
  def show
    @search = params[:search].downcase

    @chapters = Chapter.all.map do |chapter|
      chapter if chapter.name.downcase.include?(@search)
    end.compact

    @subsections = Subsection.all.map do |subsection|
      subsection if subsection.name.downcase.include?(@search)
    end.compact

    @blocks = Block.all.map do |block|
      block if block.content.downcase.include?(@search) || block.comment.downcase.include?(@search) || block.link.downcase.include?(@search)
    end.compact
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :find_block, only: [:edit, :destroy, :switch, :switch_update]
  # вызывает ошибку мол несколько раз вызываю редирект
  # after_action :redirect_block, only: [:create, :update, :destroy]

  def create
    @block = BlockSave.(params)
    redirect_block
  end

  def update
    @block = BlockUpdate.(params.permit!)
    redirect_block
  end

  def edit
  end

  def destroy
    @block.destroy
    redirect_block
  end

  def switch
  end

  def switch_update
    if !params[:chapter_id].nil?
      @block.chapter = Chapter.find params[:chapter_id]
      @block.subsection = nil
      @block.save
    elsif !params[:subsection_id].nil?
      @block.subsection = Subsection.find params[:subsection_id]
      @block.chapter = nil
      @block.save
    end

    redirect_block
  end

  private

  def find_block
    @block = Block.find params[:id]
  end

  def redirect_block
    unless @block.nil?
      if @block.chapter.nil?
        flash[:success] = I18n.t('block.comments.edit')
        redirect_to subsection_path(@block.subsection)
      else
        flash[:success] = I18n.t('block.comments.edit')
        redirect_to chapter_path(@block.chapter)
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_chapter, only: [:show, :edit]

  def index
    @chapters = Chapter.order(count_clicks: :DESC)
    @last_updated_chapter = Chapter.order(updated_at: :desc).first
  end

  def new
    @chapter = Chapter.new
    @block = Block.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      flash[:success] = I18n.t('chapter.comments.create')
    else
      flash[:danger] = @chapter.errors[:name].first
    end

    BlockSave.(params)
    redirect_to root_path
  end

  def show
    # фиксируем клик, нужно для активности
    # LinkClickedJob.perform_later(@chapter)
    LinkClickedJob.set(wait: 10.second).perform_later(@chapter)
  end

  def edit
    @subsection = Subsection.new
    @block = Block.new
  end

  def update
    @chapter = Chapter.find params[:id]
    @chapter.update(chapter_params)

    flash[:success] = I18n.t('chapter.comments.edit')
    redirect_to chapter_path(@chapter)
  end

  def destroy
    redirect_to root_path
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name, :count_clicks)
  end

  def find_chapter
    @chapter = Chapter.find(params[:id])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_action :find_error, only: [:show]

  def index
    @errors = Error.all
  end

  def new
    @error = Error.new
  end

  def create
    @error = Error.create(error_params)
    redirect_to root_path
  end

  def show
  end

  private

  def find_error
    @error = Error.find params[:id]
  end

  def error_params
    params.require(:error).permit(:name, :description, :correct)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  COLOR = ['warning', 'success', 'primary']

  def index
    @tasks = Task.order(:status).order(updated_at: :desc)
    @colors = COLOR
  end

  def show
  end

  def edit
  end

  def update
    Task.find(params[:id]).update(task_params)
    redirect_to tasks_path
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  private

  def task_params
    params.require(:task).permit(:title, :status)
  end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/subsections_helper.rb
module SubsectionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/ajax.html.erb
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dairy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <div class="row bg-info p-2">
      <div class="row col-10 m-auto">
        <div class="col-4">
          <%= link_to t("chapter.main"), root_path, class: "btn btn-dark" %>
          <%= link_to t("message.back"), :back, class: "btn btn-dark" %>
          <%= link_to t("chapter.create"), new_chapter_path, class: "btn btn-dark" %>
        </div>

        <div class="col-3">
          <%= text_field_tag :search, nil, placeholder: t("message.search"), class: "mb-2 w-100" %>
        </div>

        <div class="col-4">
          <%= link_to t("error.name"), errors_path, class: "btn btn-dark" %>
          <%= link_to t("error.create"), new_error_path, class: "btn btn-dark" %>
          <%= link_to t("tasks.name"), tasks_path, class: "btn btn-dark" %>
        </div>
        <%= link_to "CARGO", cargo_orders_path, class: "btn btn-success w-auto" %>
      </div>
    </div>

    <div class="col-11 m-auto">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%=key %> m-2" id="win-message">
          <button class="btn btn-close float-end" id="btn-close"></button>
          <%= value %>
        </div>
      <% end %>

    <div id="conteiner"><%= yield %></div>
    </div>
  </body>
</html>

app/views/layouts/cargo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CARGO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>
  <!-- f0ddb9  bdffe3  a8a49d -->
  <body>
    <div class="row bg-info p-2 mb-2">
      <div class="row col-10 m-auto">
        <%= link_to "DIARY", root_path, class: "btn btn-dark w-auto mx-1" %>
        <%= link_to "BACK", :back, class: "btn btn-success w-auto mx-1" %>
        <%= link_to "ORDERS", cargo_orders_path, class: "btn btn-success w-auto mx-1" %>
        <%= link_to "CUSTOMERS", cargo_customers_path, class: "btn btn-success w-auto mx-1" %>
        <%= link_to "CARRIERS", cargo_carriers_path, class: "btn btn-success w-auto mx-1" %>
        <%= link_to "TOWNS", cargo_towns_path, class: "btn btn-success w-auto mx-1" %>
      </div>
    </div>

    <div class="col-11 m-auto">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%=key %> m-2" id="win-message">
          <button class="btn btn-close float-end" id="btn-close"></button>
          <%= value %>
        </div>
      <% end %>

    <div id="conteiner"><%= yield %></div>
    </div>
  </body>
</html>